"""CodeQL parser stub header.

Provides libc/Ghidra typedefs, decompiler helper macros, and common API
prototypes so --build-mode=none can parse the reconstructed C. A missing
typedef makes the parser drop the whole statement (and any taint source/sink
inside it), so declarations are kept deliberately broad.

Include strategy (revised 2026-07):
  1. Prefer #include for standard-library headers so CodeQL recognises
     library functions and applies its built-in TaintTracking models.
     Manually-declared functions do not trigger built-in models even when
     the signature matches, breaking taint at strchr/strlen/etc.
  2. Keep Ghidra-specific types and decompiler helper macros.
  3. Keep firmware-specific function declarations (non-standard-library).
  4. Avoid headers that conflict with empty-body structs in recopilot_types.h:
     - <sys/stat.h> conflicts with struct stat — manually declare stat family
     - <netinet/in.h> conflicts with struct sockaddr_in — manually declare
       inet/byteorder family
     - <sys/socket.h> may transitively include <netinet/in.h> — manually
       declare socket family
     These manual declarations are not critical taint-propagation nodes
     (sources/sinks come from CLARIS config) and do not depend on CodeQL
     built-in models.
"""
from __future__ import annotations

from pathlib import Path

from pipeline.paths import STUB_HEADER_FILENAME

STUB_HEADER = r"""#ifndef RECOPILOT_STUBS_H
#define RECOPILOT_STUBS_H

#ifndef NULL
#define NULL ((void *)0)
#endif

/* === Standard-library headers ================================
   Let CodeQL recognise library function identity and apply its built-in
   TaintTracking models. Under --build-mode=none, CodeQL uses its built-in
   C/C++ frontend preprocessor, which handles these headers.

   Name collisions with structs generated by the Ghidra registry in
   recopilot_types.h are resolved by STANDARD_LIB_STRUCTS exclusion logic
   in pipeline/registry/header.py: types.h skips rendering of
   stat/sockaddr_in/timeval/fd_set/passwd and other standard-library
   structs; definitions come from these #includes instead. */
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <time.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdarg.h>
#include <ctype.h>
#include <signal.h>
#include <setjmp.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/stat.h>
#include <dlfcn.h>
#include <syslog.h>
#include <pwd.h>
#include <netdb.h>

/* === Ghidra pseudo-types (not in standard headers) =========== */
typedef unsigned char undefined;
typedef unsigned char undefined1;
typedef unsigned short undefined2;
typedef unsigned int undefined4;
typedef unsigned long long undefined8;
typedef void code;

typedef unsigned int uint;
typedef unsigned short ushort;
typedef unsigned long ulong;
typedef long long longlong;
typedef unsigned long long ulonglong;

typedef unsigned char byte;
typedef unsigned short word;
typedef unsigned int dword;
typedef unsigned long long qword;

typedef struct {
    ulonglong lo;
    ulonglong hi;
} _OWORD;
typedef unsigned char _BYTE;
typedef unsigned short _WORD;
typedef unsigned int _DWORD;
typedef unsigned long long _QWORD;

/* === Ghidra decompiler helper macros ======================== */
#define CONCAT22(hi, lo) ((((uint)(ushort)(hi)) << 16) | (uint)(ushort)(lo))
#define CONCAT31(hi, lo) ((((uint)(hi) & 0x00ffffffU) << 8) | (uint)(byte)(lo))
#define CONCAT44(hi, lo) ((((ulonglong)(uint)(hi)) << 32) | (ulonglong)(uint)(lo))
#define CARRY4(x, y) ((uint)(x) > (0xffffffffU - (uint)(y)))
#define SCARRY4(x, y) ((((int)(x) < 0) == ((int)(y) < 0)) && \
                       (((int)((uint)(x) + (uint)(y)) < 0) != ((int)(x) < 0)))
#define SBORROW4(x, y) ((((int)(x) < 0) != ((int)(y) < 0)) && \
                        (((int)((uint)(x) - (uint)(y)) < 0) != ((int)(x) < 0)))

/* === Non-standard-library functions requiring manual declarations */
/* ioctl is provided by <sys/ioctl.h>, but CodeQL's built-in model
   coverage for it is incomplete, and the request parameter type varies
   across platforms. Declared manually to be safe. */
int ioctl(int fd, unsigned long request, ...);

/* === glibc LFS variants and internal functions ===============
   Ghidra decompiles fopen/open/fcntl into *64 variants (LFS Large File
   Summit). These are not in CodeQL's built-in standard-library models,
   but must be declared to prevent statements from being silently dropped. */
FILE *fopen64(const char *pathname, const char *mode);
int open64(const char *pathname, int flags, ...);
int fcntl64(int fd, int cmd, ...);
int *__errno_location(void);

/* === Firmware-specific functions (non-standard-library) ====== */
int doSystemCmd(const char *format, ...);
int CsteSystem(const char *command);
int ExecShell(const char *command);
int ___system(const char *command);

#endif /* RECOPILOT_STUBS_H */
"""


def write_stub_header(codeql_dir: Path) -> None:
    codeql_dir.mkdir(parents=True, exist_ok=True)
    (codeql_dir / STUB_HEADER_FILENAME).write_text(STUB_HEADER, encoding="utf-8")
